# Generated by Django 3.2.dev20201005102505 on 2021-07-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('type', models.IntegerField()),
            ],
        ),
    ]
