# Generated by Django 3.2.dev20201005102505 on 2021-07-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='studentid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
