# Generated by Django 3.2.dev20201005102505 on 2021-07-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_watchlist_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='studentid',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
