# Generated by Django 3.2.dev20201005102505 on 2021-07-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_watchlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='img',
            field=models.ImageField(default=1, upload_to='static\\img'),
            preserve_default=False,
        ),
    ]
