# Generated by Django 3.2.dev20201005102505 on 2021-07-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_watchlist_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='img',
            field=models.ImageField(null=True, upload_to='images/ '),
        ),
    ]
