# Generated by Django 3.2.dev20201005102505 on 2021-07-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_watchlist_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='img',
            new_name='image',
        ),
    ]
