# Generated by Django 3.2.dev20201005102505 on 2021-07-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_watchlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='image',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
