# Generated by Django 3.2.dev20201005102505 on 2021-07-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_watchlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
